[CBW-1097] Now displaying NFT name in collectables tab and send funds.
Concordium/concordium-reference-wallet-android pull request #246
Opened 2023-06-20 10:57 UTC by czerwix

## Changes

[CBW-1097] Now displaying NFT name in collectables tab and send funds.

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [x] I accept the above linked CLA.

[CBW-1097]: https://concordium.atlassian.net/browse/CBW-1097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-06-20 13:48 UTC, orhoj requested changes

2023-06-20 13:48 UTC, orhoj commented on app/src/main/java/com/concordium/wallet/ui/cis2/TokensAccountDetailsAdapter.kt
> +                if (token.tokenMetadata?.unique == true) {
```suggestion
                if (tokenMetadata.unique) {
```

2023-06-20 13:56 UTC, shjortConcordium commented on app/src/main/java/com/concordium/wallet/ui/cis2/TokensAccountDetailsAdapter.kt
> +                        subTitle.text = if (token.totalBalance > BigInteger.ZERO) {
This subTitle is not reset/hidden for the CCD token

2023-06-20 13:56 UTC, shjortConcordium commented on app/src/main/res/layout/search_token_result.xml
I think it makes sense that we show the names of FT's as well, when selecting which token to transfer.
We do that in the browser wallet (we also have it left aligned)
![Screenshot from 2023-06-20 15-51-07](https://github.com/Concordium/concordium-reference-wallet-android/assets/87635671/c45f8e54-681d-490b-aebe-0b3b0d7bdfe7)

2023-06-20 14:43 UTC, shjortConcordium approved these changes

2023-06-21 06:41 UTC, orhoj approved these changes

2023-06-21 06:56 UTC, merged