[CBW-1037] Removed the ability to select other tokens when transferri…
Concordium/concordium-reference-wallet-android pull request #254
Opened 2023-07-10 10:33 UTC by czerwix

## Changes

[CBW-1037] "Send funds" screen options are same when opened from token details and when from account details screens

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [x] I accept the above linked CLA.

[CBW-1037]: https://concordium.atlassian.net/browse/CBW-1037?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-07-10 12:01 UTC, shjortConcordium approved these changes
LGTM, though it's annoying that 90% of the changes seem to irrelevant refactors :upside_down_face:

2023-07-10 14:16 UTC, orhoj requested changes

2023-07-10 14:16 UTC, orhoj commented on CHANGELOG.md
> +## [1.20]
```suggestion
## [1.2.0]
```

2023-07-10 14:16 UTC, orhoj commented on CHANGELOG.md
> +## [1.20]
I assume it is not 1.20 :smile:

2023-07-14 11:13 UTC, orhoj approved these changes

2023-07-15 07:51 UTC, merged