[CBW-1440] added support for concordiumwallet://wc deeplink
Concordium/concordium-reference-wallet-android pull request #308
Opened 2023-10-26 08:43 UTC by TouHouNo

## Changes

 added support for new concordiumwallet://wc deeplink

for testing please push an intent with the command `adb shell am start -W -a android.intent.action.VIEW -d "concordiumwallet://wc" software.concordium.mobilewallet.seedphrase.testnet`

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [x] (If necessary) I have updated the CHANGELOG.

## CLA acceptance

_Remove if not applicable.

By submitting the contribution I accept the terms and conditions of the
Contributor License Agreement v1.0
- link: https://developers.concordium.com/CLAs/Contributor-License-Agreement-v1.0.pdf

- [x] I accept the above linked CLA.

2023-10-26 11:23 UTC, orhoj requested changes

2023-10-26 11:23 UTC, orhoj commented on app/src/main/AndroidManifest.xml
> +                <data
You can just put this `<data>` clause inside the existing `intent-filter` above.

2023-10-26 11:23 UTC, orhoj commented on app/src/main/java/com/concordium/wallet/ui/MainActivity.kt
> +            if (it.toString().startsWith("wc") || it.toString()
These lines are duplicated twice below, so create a helper function to perform the check instead.

I don't really understand why it needs to set `wcUri` in both places in the intents, but I guess it's easier to just keep that as is.

2023-10-26 11:23 UTC, orhoj commented on app/src/main/java/com/concordium/wallet/ui/recipient/scanqr/ScanQRViewModel.kt
> +        return qrInfo.isNotBlank() && (qrInfo.lowercase().startsWith("wc:") || qrInfo.lowercase()
For the QR code we don't need to support anything but `wc` for the format. The QR codes generated by WalletConnect are all just using `wc:`, so unless someone built something custom we won't see such QR codes. And I guess that won't be needed as you are already in the app when scanning.

2023-10-31 08:53 UTC, orhoj commented
Will wait to approve until Shashi has tested.

2023-11-13 11:47 UTC, shjortConcordium approved these changes

2023-11-14 09:38 UTC, merged