Use BigInteger for stake amounts
Concordium/concordium-reference-wallet-android pull request #325
Opened 2024-02-09 14:44 UTC by Radiokot

Also fixes CBW-1611.
Now the minimum stake amount is not checked
if not changing the amount while updating the status.

2024-02-09 15:38 UTC, ramakser approved these changes

2024-02-13 12:16 UTC, orhoj requested changes

2024-02-13 12:26 UTC, orhoj commented on app/src/main/java/com/concordium/wallet/data/model/AccountBaker.kt
> +    val stakedAmount: BigInteger,
It seems that `GlobalTypeConverters.kt` already defines a `BigInteger` converter that should be compatible with the existing String values, so I suppose this has no impact on the database.

2024-02-13 12:47 UTC, Radiokot commented on app/src/main/java/com/concordium/wallet/data/model/AccountBaker.kt
> +    val stakedAmount: BigInteger,
The `AccountBaker` model is stored as JSON. The JSON serializer writes `BigInteger` as string, and vice versa. The same goes for API requests.
https://github.com/Concordium/concordium-reference-wallet-android/blob/e54403d38eb63ca160455d0ac37e9f7b0cebc804/app/src/main/java/com/concordium/wallet/data/room/typeconverter/AccountTypeConverters.kt#L47-L63
https://github.com/Concordium/concordium-reference-wallet-android/blob/e54403d38eb63ca160455d0ac37e9f7b0cebc804/app/src/main/java/com/concordium/wallet/AppCore.kt#L50
https://github.com/Concordium/concordium-reference-wallet-android/blob/e54403d38eb63ca160455d0ac37e9f7b0cebc804/app/src/main/java/com/concordium/wallet/core/gson/BigDecimalTypeAdapter.kt

2024-02-14 11:51 UTC, orhoj approved these changes

2024-02-14 12:06 UTC, merged